### ISSUE TITLE
TP04: Scrollable List

### ISSUE THREAD

**Issue by SitiShafira** [indraazimi/galeri-hewan#1]
Nama: Siti Shafira
NIM: 6706204040
Kelas: D3 RPLA 44-04

1.	Apa fungsi version control system (VCS) seperti Git? Apa beda Git dengan Github?
Jawab:
Version Control System berfungsi untuk membantu penyimpanan berupa history tanpa menyimpan file baru, yang tersimpan hanya perubahan data. Sehingga kapasitas penyimpanan file menjadi ringan.
Perbedaan Git dan Github:
-	Git meng-install software di penyimpanan local, sedangkan github Host melalui layanan cloud.
-	Git Berfokus pada version control dan code sharing, sedangkan Github Berfokus pada source code hosting terpusat.
-	Git dapat diakses secara offline, sedangkan Github dapat diakses secara online.

2.	Menampilkan data berupa list menggunakan RecyclerView akan lebih efisien, karena ada proses recycling. Jelaskan konsep recycling pada RecyclerView!
Jawab:
Hanya menggunakan tampilan dalam jumlah terbatas yang digunakan kembali saat tampilan tersebut tidak tampak di layar. Hal ini menghemat memori dan mempercepat pembaruan item daftar saat pengguna menggulir data, karena tidak perlu membuat tampilan baru untuk setiap item yang muncul.

3.	RecyclerView terdiri dari 3 komponen, yaitu item data, adapter dan view holder seperti terlihat pada gambar. Jelaskan fungsi dari masing-masing komponen!
Jawab:
-Data:
Data ini akan di representasikan sebagai sebuah file models dalam project android. Models di desain sesuai dengan kebutuhan dari data yang ditampilkan pada recyclerview, data dapat berupa tulisan, gambar, atau angka yang muncul pada desain recyclerview.
-Adapter:
Dalam RecyclerView, adapter menghubungkan data dengan tampilan. Adapter bertindak sebagai perantara antara data dan tampilan. Adapter menerima atau mengambil data, melakukan semua pekerjaan yang diperlukan agar bisa ditampilkan dalam suatu tampilan, dan menempatkan data dalam tampilan.
-View holder:
menjelaskan tampilan data dan metadata tentnag tempatnya dalam RecyclerView. Setiap view holder menampung satu rangkaian data. Adapter menambahkan data ke view holder untuk ditampilkan oleh pengelola layout.

4.	Terdapat 3 buah method yang harus kita override ketika menggunakan RecyclerView.Adapter. Tuliskan nama-nama method tersebut beserta fungsinya masing-masing!
Jawab:
-	‘getItemCount()’ berfungsi untuk menentukan jumlah item yang akan ditampilkan. Jika method ini mengembalikan nilai 1, artinya hanya akan ada 1 item yang ditampilkan.
-	‘onCreateViewHolder()’ berfungsi untuk membuat objek ViewHolder. Di method ini kita juga akan menentukan layout XML yang akan digunakan untuk setiap item.
-	‘onBindViewHolder()’ berfungsi untuk menghubungkan data yang ada dengan objek ViewHolder.

5.	Bagaimana cara agar item pada RecyclerView dapat diklik? Jelaskan langkah-langkahnya!
Jawab:
-	Pada list_item.xml, tambahkan baris ini agar dapat menampilkan efek ripple ketika di klik:
android:background="?android:selectableItemBackground"
-	Tambahkan baris ini di strings.xml:
<string name=”message”>%1$s diklik! </string>
-	Tambahkan click listener pada method bind di ViewHolder:
root.setOnClickListener {
 val message = root.context.getString(R.string.message, hewan.nama) Toast.makeText(root.context, message, Toast.LENGTH_LONG).show() 
}

**Comment by indraazimi** [comment]
TP dikerjakan di issue repository praktikum masing2, bukan di repo ini. Repository untuk praktikum didapat dari Github assignment yang link nya diberikan oleh dosen kelas.
